CFLAGS += -g -Wall
CFLAGS += -O2
CFLAGS += $(INCLUDE)

LDFLAGS += -L$(LIBARM) -larmvm

LIBARM += git/libarmvm

INCLUDE += -Iinclude
INCLUDE += -I../git
INCLUDE += -I..

VPATH += source
VPATH += ../

all: test

test: test.o test_arm.a

TEST_ARM_OBJS += test_arm.o \
	test_arm_b_bl.o

test_arm.a: test_arm.a(%TEST_ARM_OBJS)

clean:
	-rm *.d *.o

clean_all: clean clean_logs
	-rm *.a

clean_logs:
	-rm *.debug *.log *.trace
