TOP_DIR = $(PWD)
GIT_DIR = $(TOP_DIR)/git

OBJ_DIR = $(TOP_DIR)/build-$(shell $(CC) -dumpmachine)

ARFLAGS += -U

CFLAGS += -g -Wall -Wextra
CFLAGA += -O2 -march=native
CFLAGS += -Werror
CFLAGS += -MMD -MP
CFLAGS += $(INCLUDE)

INCLUDE += -I$(TOP_DIR)/include
INCLUDE += -I$(GIT_DIR)
